version: '3.9'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=library

volumes:
  pgdata: